---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: nginx-service-port
      protocol: TCP
      port: 8080
      targetPort: 80  
